name: Test deployment with Bun

on:
  pull_request:
    branches:
      - main

env:
  GTAG_TRACKING_ID: ${{ secrets.GTAG_TRACKING_ID }}
  
jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Test build website
        run: bun run build
